name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: guardian/actions-setup-node@main
      - uses: bahmutov/npm-install@v1
      - run: yarn lint:check
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: guardian/actions-setup-node@main
      - uses: bahmutov/npm-install@v1
      - run: yarn build
